# This file is automatically generated by "https://github.com/2moe/cinnabar/raw/refs/heads/main/misc/utils/99_autogen_cinnabar.rb"
# Please edit with caution.
#
# frozen_string_literal: true

require_relative 'cinnabar/00_pre'
require_relative 'cinnabar/cmd_runner'
require_relative 'cinnabar/gem_path'
require_relative 'cinnabar/net'
require_relative 'cinnabar/path'
require_relative 'cinnabar/pipe'
require_relative 'cinnabar/utils'
require_relative 'cinnabar/version'
