#!/usr/bin/env -S ruby --disable=gems
# typed: false
# frozen_string_literal: true

# ----------------
require_relative 'enter_misc_dir'
Dir.chdir('../lib')
final_file = 'cinnabar.rb'

def extra_inline_expr(name)
  mod_name =
    case File.basename name
      when 'gem_path'
        'Cinnabar::GemPathCore'
      when 'utils'
        'Cinnabar::Utils'
      else ()
    end

  return '' if mod_name.nil?

  "unless defined? #{mod_name}"
end

exprs =
  Dir['cinnabar/*.rb']
    .map { _1.chomp('.rb') }
    .map { |name|
      %(require_relative '#{name}' #{extra_inline_expr(name)}).chomp(' ')
    }
    .push('')

File.open(final_file, 'w+') do |out_file|
  [
    '# This file is automatically generated by "https://github.com/2moe/cinnabar/raw/refs/heads/main/misc/utils/99_autogen_cinnabar.rb"',
    '# Please edit with caution.',
    '#',
    '# frozen_string_literal: true',
    '',
  ].concat(exprs)
    .join("\n")
    .then { out_file.write(_1) }
end
