#!/usr/bin/env -S ruby --disable=gems
# typed: false
# frozen_string_literal: true

# ----------------
require_relative 'enter_misc_dir'
Dir.chdir('../lib')
final_file = 'cinnabar.rb'

exprs =
  Dir['cinnabar/*.rb']
    # .sort
    .map { %(require_relative '#{_1.chomp('.rb')}') }
    .push('')

File.open(final_file, 'w+') do |out_file|
  [
    '# This file is automatically generated by "https://github.com/2moe/cinnabar/raw/refs/heads/main/misc/utils/99_autogen_cinnabar.rb"',
    '# Please edit with caution.',
    '#',
    '# frozen_string_literal: true',
    '',
  ].concat(exprs)
    .join("\n")
    .then { out_file.write(_1) }
end
