#!/usr/bin/env -S ruby --disable=gems
# frozen_string_literal: true

# disable Lint/MissingCopEnableDirective, rubocop:disable Style/FrozenStringLiteralComment
# ----------------
require_relative 'enter_ci_dir'

argvise_rb = Pathname 'tmp/argvise.rb'

raise "File #{argvise_rb} does not exist or is empty." unless
  argvise_rb.exist? && argvise_rb.size > 16

[
  '# This file is automatically generated by "https://github.com/2moe/glossa/raw/refs/heads/dev/ci/utils/concat.rb". Please edit with caution.', # rubocop:disable Layout/LineLength
  argvise_rb.read,
  File.read('misc/end.rb')
]
  .join("\n")
  .then { File.write('preload.rb', it) }
